# -*- coding: utf-8 -*-
"""Copy of Applied_Tech_Project_7_Question_copy_v0.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19eaJOoCZZ4TTxX8NazsIB-N5Wk9UrVrw

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Variables and Data-Types
 2. Python Lists II

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

   https://drive.google.com/file/d/1QLXHJB-tjhq0HhdB8ZGi1K5TJuYd49ht/view?usp=sharing
2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project7** format.

4. Now, write your code in the prescribed code cells.

---

### Activities

#### Activity 1: Swapping numbers

Accept two numbers from the user. Store these numbers in two variables and swap the values of these variables.

**Example**:

```
num1: 10
num2: 25
Value of num1 after swapping:  25
Value of num2 after swapping:  10
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Ask the user to enter two different numbers and store them in variables `num1` and `num2` respectively.

  - **Step 2**: Declare one more variable `temp` which will be used to swap the values between `num1` and `num2`. Assign the value of `num1` variable to the `temp` variable.

  - **Step 3**: Assign the value of `num2` variable to `num1` variable.

  - **Step 4**: Assign the value of `temp` variable to `num2` variable.

  - **Step 5**: Print the values of `num1` and `num2` variables obtained after swapping.
"""

# Write your code here
# Step 1: Ask user to enter two numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Step 2: Declare a temporary variable 'temp' and assign the value of 'num1' to it
temp = num1

# Step 3: Assign value of 'num2' to 'num1'
num1 = num2

# Step 4: Assign value of 'temp' to 'num2'
num2 = temp

# Step 5: Print the values of 'num1' and 'num2' after swapping
print("The value of num1 after swapping is:", num1)
print("The value of num2 after swapping is:", num2)

"""---

#### Activity 2: Multiplying numbers of the list

Create a list which contains some numbers and multiply all the numbers in the list.

**Constraint:** The list should not be empty.

For Example:

```
list[1,2,3] will give '6'
list[2,3,7] will give '42'
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Declare a list `num_list` containing some numbers.

  - **Step 2**: Use `len()` function to find the length of the list and store it in `length` variable.

  - **Step 3**: Initialize two variables:

    1. `i = 0` (To hold index number needed for list indexing. As index always starts with `0`, that is why this variable is initialized to `0`.)
    
    2. `result = 1` (To store the product of numbers)

  - **Step 4**: Use a `while` loop. This loop continues to iterate till all the numbers of the list are multiplied i.e. the condition for `while` loop to iterate is `i<length`.

  - **Step 5**: Inside this `while` loop, perform the following tasks:
      1.  Multiply the value stored in `result` variable with each element of the list. To access each number of the list, use list indexing.
      2. Increment the value of variable `i` by `1`.

  - **Step 6**: Print the result.
"""

# Write your code here
# Step 1: Declare a list of numbers
num_list = [3, 4, 5, 6]

# Step 2: Find the length of the list
length = len(num_list)

# Step 3: Initialize variables
i = 0
result = 1

# Step 4: Iterate through the list using a while loop
while i < length:
    # Step 5: Multiply each element of the list with 'result'
    result *= num_list[i]
    i += 1

# Step 6: Print the final result
print("The product of all numbers in the list is:", result)

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project7**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project7** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""